all:
  master_email: lagden@gmail.com
  #
  session_user_id: user_id
  session_user_name: user_name
  session_user_credential: user_credential
  #
  admin_credential: administrador
  editor_credential: editor
  #
  search:
    max_per_page: 30