# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT | E_NOTICE) & ~E_DEPRECATED)."\n" ?>
    web_debug:              false
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT | E_NOTICE) & ~E_DEPRECATED)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .actions:
    error_404_module:       default
    error_404_action:       error404

    login_module:           auth
    login_action:           index

    secure_module:          default
    secure_action:          secure

    module_disabled_module: default
    module_disabled_action: disabled

  .settings:
    # Form security secret (CSRF protection)
    # csrf_secret:            59da2e7bc650d465e236ee2817658758c4122198

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
