<?php

/**
 * ComplementoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComplementoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComplementoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Complemento');
    }
}