<?php

/**
 * ContentTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContentTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContentTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContentTag');
    }
}