<?php

/**
 * DisponibilidadeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DisponibilidadeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DisponibilidadeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Disponibilidade');
    }
}