<?php

/**
 * EstateDisponibilidadeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstateDisponibilidadeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstateDisponibilidadeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstateDisponibilidade');
    }
}