<?php

/**
 * EstateTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstateTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstateTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstateTag');
    }
}