<?php

/**
* EstateTable
* 
* This class has been auto-generated by the Doctrine ORM Framework
*/
class EstateTable extends Doctrine_Table
{
    static public $valor_venda = array(
        '' => 'Inferente',
        '< 250000' => 'até R$250.000',
        '250000 AND 450000' => 'de R$250.000 até R$450.000',
        '450000 AND 650000' => 'de R$450.000 até R$650.000',
        '650000 AND 900000' => 'de R$650.000 até R$900.000',
        '900000 AND 1500000' => 'de R$900.000 até R$1.500.000',
        '> 1500000' => 'acima de R$1.500.000',
    );
    
    static public $valor_aluguel = array(
        '' => 'Inferente',
        '< 1500' => 'até R$1.500',
        '1500 AND 2000' => 'de R$1.500 até R$2.000',
        '2000 AND 2500' => 'de R$2.000 até R$2.500',
        '> 2500' => 'acima de R$2.500',
    );
    
    static public $area = array(
        '' => 'Inferente',
        '< 50' => 'até 50m²',
        '50 AND 100' => 'de 50m² até 100m²',
        '100 AND 150' => 'de 100m² até 150m²',
        '150 AND 200' => 'de 150m² até 200m²',
        '200 AND 250' => 'de 200m² até 250m²',
        '250 AND 300' => 'de 250m² até 300m²',
        '> 300' => 'acima de 300m²',
    );
    
    static public $numbers = array(
        '' => 'Inferente',
        '1' => '1',
        '2' => '2',
        '3' => '3',
        '4' => '4',
        '> 4' => '5 ou mais',
    );
    
    public function getValorVenda()
    {
        return self::$valor_venda;
    }
    
    public function getValorAluguel()
    {
        return self::$valor_aluguel;
    }
    
    public function getArea()
    {
        return self::$area;
    }
    
    public function getNumbers()
    {
        return self::$numbers;
    }
    
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estate');
    }
}