<?php

/**
* Estate
* 
* This class has been auto-generated by the Doctrine ORM Framework
* 
* @package    sfProject
* @subpackage model
* @author     Thiago Lagden
* @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
*/
class Estate extends BaseEstate
{
    public function getJoinDisponibilidades()
    {
        return static::getJoin($this->Disponibilidades);
    }
    
    public function getJoinTags()
    {
        return static::getJoin($this->Tags);
    }
    
    static public function getJoin($es,$f='name')
    {
        $arr = array();
        foreach ($es as $e) {
            $arr[]=$e->$f;
        }
        return join(', ',$arr);
    }
}
