<?php

/**
 * EstateComplementoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstateComplementoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstateComplementoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstateComplemento');
    }
}