<?php

/**
 * FormatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FormatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FormatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Format');
    }
}