<?php

/**
* ImageTable
*
* This class has been auto-generated by the Doctrine ORM Framework
*/
class ImageTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ImageTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Image');
  }

 // Table Class Name
  public static function className()
  {
    return get_class(static::getInstance());
  }

  // Uploads path
  public static function dir()
  {
    return
      sfConfig::get('sf_upload_dir') .
      DIRECTORY_SEPARATOR .
      static::className();
  }
}
