<?php

/**
 * ImageVersionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImageVersionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImageVersionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ImageVersion');
    }
}