<?php

/**
 * LogReportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogReportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogReportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LogReport');
    }
}