<?php

/**
* NeighborhoodTable
* 
* This class has been auto-generated by the Doctrine ORM Framework
*/
class NeighborhoodTable extends Doctrine_Table
{
    /**
    * Returns an instance of this class.
    *
    * @return object NeighborhoodTable
    */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Neighborhood');
    }
    
    public function findOneByNameOrCreate($name, $city)
    {
        if (! $name)
        {
            return null;
        }
        
        
        $item = $this->getBairro($name, $city)->fetchOne();
        if (! $item)
        {
            $item = new Neighborhood();
            $item->city_id = $city;
            $item->name = $name;
            $item->save();
        }
        return $item;
    }
    
    public function getBairro($bairro, $city, Doctrine_Query $q = null)
    {
        if (null === $q) $q = $this->getListQuery();
        $alias=$q->getRootAlias();
        $q->andWhere("{$alias}.city_id = :v", array(':v'=>"{$city}"));
        $q->andWhere("{$alias}.name LIKE :q", array(':q'=>"{$bairro}"));
        $q->limit(1);
        return $q;
    }
    
    // Filtro
    public function getListFilter(array $filters, Doctrine_Query $q = null)
    {
        return Filter::query($filters,sfContext::getInstance()->getUser()->getAttribute('search_list.fields'),static::getInstance());
    }

    public function getListQuery(Doctrine_Query $q = null)
    {
        if(null === $q)$q = $this->createQuery('a');
        return $q;
    }
}