<?php

/**
 * NeighborhoodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NeighborhoodTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NeighborhoodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Neighborhood');
    }
}