<?php

/**
 * SectionTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SectionTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SectionTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SectionTag');
    }
}