<?php

/**
* TagTable
* 
* This class has been auto-generated by the Doctrine ORM Framework
*/
class TagTable extends Doctrine_Table
{
    /**
    * Returns an instance of this class.
    *
    * @return object TagTable
    */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tag');
    }

    public function findByNameOrCreate($tags)
    {
        if (! is_array($tags))
        {
            $tags = preg_split('/\s*,\s*/', $tags, null, PREG_SPLIT_NO_EMPTY);
        }

        $output = array();
        foreach ($tags as $tagName)
        {
            $tag = $this->findOneByName($tagName);
            if (! $tag)
            {
                $tag = new Tag;
                $tag->name = $tagName;
                $tag->save();
            }
            $output[]=$tag->id;
        }
        return $output;
    }

    // Filtro
    public function getListFilter(array $filters, Doctrine_Query $q = null)
    {
        return Filter::query($filters,sfContext::getInstance()->getUser()->getAttribute('search_list.fields'),static::getInstance());
    }

    public function getListQuery(Doctrine_Query $q = null)
    {
        if(null === $q)$q = $this->createQuery('a');
        return $q;
    }
}