<?php

/**
* TypeTable
* 
* This class has been auto-generated by the Doctrine ORM Framework
*/
class TypeTable extends Doctrine_Table
{
    /**
    * Returns an instance of this class.
    *
    * @return object TypeTable
    */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Type');
    }

    public function findOneByNameOrCreate($name)
    {
        if (! $name)
        {
            return null;
        }
        $item = $this->getTipo($name)->fetchOne();
        if (! $item)
        {
            $item = new Type();
            $item
                ->setName($name)
                ->save();
        }
        return $item;
    }

    public function getTipo($tipo, Doctrine_Query $q = null)
    {
        if (null === $q) $q = $this->getListQuery();
        $alias=$q->getRootAlias();
        $q->andWhere("{$alias}.name = :v", array(':v'=>"{$tipo}"));
        $q->limit(1);
        return $q;
    }

    // Filtro
    public function getListFilter(array $filters, Doctrine_Query $q = null)
    {
        return Filter::query($filters,sfContext::getInstance()->getUser()->getAttribute('search_list.fields'),static::getInstance());
    }

    public function getListQuery(Doctrine_Query $q = null)
    {
        if(null === $q)$q = $this->createQuery('a');
        return $q;
    }
}