<?php
/**
* UserTable
* 
* This class has been auto-generated by the Doctrine ORM Framework
*/
class UserTable extends Doctrine_Table
{
    public static function getInstance()
    {
        return Doctrine_Core::getTable('User');
    }

    public function getValidatedUserQuery($login, $password, Doctrine_Query $q = null)
    {
        if (null === $q) $q = $this->getListQuery();
        $q->andWhere($q->getRootAlias().'.login = ?', $login);
        $q->andWhere($q->getRootAlias().'.password = ?', User::encryptPassword($password));
        return $q;
    }

    public function getValidatedUser($login, $password)
    {
        return $this->getValidatedUserQuery($login, $password)->fetchOne();
    }

    // Filtro
    public function getListFilter(array $filters, Doctrine_Query $q = null)
    {
        return Filter::query($filters,sfContext::getInstance()->getUser()->getAttribute('search_list.fields'),static::getInstance());
    }

    public function getListQuery(Doctrine_Query $q = null)
    {
        if(null === $q)$q = $this->createQuery('a');
        return $q;
    }
}
