<?php

/**
* User
* 
* This class has been auto-generated by the Doctrine ORM Framework
* 
* @package    sfProject
* @subpackage model
* @author     Thiago Lagden
* @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
*/
class User extends BaseUser
{
    public function setPassword($password)
    {
        if ($password)
        {
            $this->_set('password', self::encryptPassword($password));
        }
        return $this;
    }

    public static function encryptPassword($password)
    {
        return strrev(sha1(strtolower($password)).sha1(strtoupper($password))); 
    }
}
