# all:
#   .array:
#     creditcards:
#       fake:             false
#       visa:             true
#       americanexpress:  true

# [php]
# print_r(sfConfig::get('app_creditcards'));
# 
# Array(
#   [fake] => false
#   [visa] => true
#   [americanexpress] => true
# )

all:
  seo: 'Apartamentos à venda em Higienópolis e Santa Cecília'
  master_email: breno@brenohomaraimoveis.com.br # colocar de acordo com o Swift_SmtpTransport
  send:
    to:
      - 'brenoimoveis@uol.com.br'
      - 'ryan@brenohomaraimoveis.com.br'
      - 'lagden@gmail.com'
  
  # Filter General for Estate
  formfilter_estate: EstateFormFilter
  app_cookie_search_estate: estate_site_search.filters
  route_form_filter: estate_filter
  search:
    max_per_page: 24
  
  .array:
    footer:
      dono: 'Breno Homara'
      func: 'Técnico em Transações Imobiliárias'
      email: 'brenoimoveis@uol.com.br'
      site: 'Breno Homara Imóveis'
      creci: 'CRECI 30231'
      endereco: 'Rua Baronesa de Itú, 275 | Higienópolis | São Paulo | 01231-001'
      telefone: '(11) 3667-0124 ou (11) 3667-9756'
      dev: 'Lagden.art.br'
      devsite: 'http://lagden.art.br/'