all:
  name: 'Breno Homara Imóveis'
  title: 'Apartamentos em Higienópolis - Breno Homara Imóveis'
  cache_version: '0.1.0'
  seo: 'Apartamentos à venda em Higienópolis e Santa Cecília'
  master_email: breno@brenohomaraimoveis.com.br # colocar de acordo com o Swift_SmtpTransport
  send:
    to:
      - 'brenoimoveis@uol.com.br'
      - 'ryan@brenohomaraimoveis.com.br'
      # - 'lagden@gmail.com'

  # Filter General for Estate
  formfilter_estate: EstateFormFilter
  app_cookie_search_estate: estate_site_search.filters
  route_form_filter: estate_filter
  search:
    max_per_page: 1

  .array:
    footer:
      dono: 'Breno Homara'
      func: 'Técnico em Transações Imobiliárias'
      email: 'contato@brenohomaraimoveis.com.br'
      site: 'Breno Homara Imóveis'
      creci: 'CRECI 30231'
      endereco: 'Rua Baronesa de Itú, 275'
      endereco2: 'Higienópolis | São Paulo'
      endereco3: '01231-001'
      telefone: '(11) 3667-0124'
      telefone2: '(11) 3667-9756'
      dev: 'Lagden.in'
      devsite: 'http://lagden.in'
