# all:
#   .array:
#     creditcards:
#       fake:             false
#       visa:             true
#       americanexpress:  true

# [php]
# print_r(sfConfig::get('app_creditcards'));
# 
# Array(
#   [fake] => false
#   [visa] => true
#   [americanexpress] => true
# )

all:
  master_email: lagden@gmail.com
  # Filter General for Estate
  formfilter_estate: EstateFormFilter
  app_cookie_search_estate: estate_site_search.filters
  route_form_filter: estate_filter
  search:
    max_per_page: 18