# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

# Module Estate
estate:
  class: sfDoctrineRouteCollection
  options:
    model: Estate
    with_show: false
    prefix_path: /imoveis
    collection_actions:
      filter: post
      clear: get

estate_page:
  url: /imoveis/busca/pagina/:pagina
  param: { module: estate, action: index }
  requirements:
    sf_method: [GET]

estate_sort:
  url: /imoveis/busca/ordena
  param: { module: estate, action: sort }
  requirements:
    sf_method: [POST]

estate_disponibilidade:
  url: /imoveis/disponibilidade
  param: { module: estate, action: disponibilidade }
  requirements:
    sf_method: [POST]

estate_referencia:
  url: /imoveis/referencia
  param: { module: estate, action: referencia }
  requirements:
    sf_method: [POST]

estate_interessou:
  url: /imoveis/interessou
  param: { module: estate, action: contato }
  requirements:
    sf_method: [POST]

estate_notfound:
  url: /imoveis/nao-encontrado
  param: { module: estate, action: notFound }

estate_show:
  url: /imoveis/mostra/:slug
  param: { module: estate, action: show }
  requirements:
    sf_method: [GET]

# Routes do site antigo (Evitar erros)
estate_old_busca:
  url: /busca
  param: { module: estate, action: index }
  requirements:
    sf_method: [GET]

estate_old_page:
  url: /busca/page/:pagina
  param: { module: estate, action: index }
  requirements:
    sf_method: [GET]

estate_old_show:
  url: /show/:slug
  param: { module: estate, action: show }
  requirements:
    sf_method: [GET]
# End old Routes

# Modulo contato
contato:
  url: /contato
  param: { module: contato, action: index }
  requirements:
    sf_method: [POST]

contato_envia:
  url: /contato/envia
  param: { module: contato, action: contato }
  requirements:
    sf_method: [POST]

# Modulo venda
venda:
  url: /anuncie
  param: { module: venda, action: index }
  requirements:
    sf_method: [POST]

venda_envia:
  url: /anuncie/envia
  param: { module: venda, action: contato }
  requirements:
    sf_method: [POST]

# Modulo site
site:
  url: /site/:slug
  param: { module: site, action: index }
  requirements:
    sf_method: [GET]

site_content:
  url: /site/:section/:slug
  param: { module: site, action: index }
  requirements:
    sf_method: [GET]

site_notfound:
  url: /site/nao-encontrado
  param: { module: site, action: notFound }

# Modulo tags
# tag:
#   url: /tag/:slug
#   param: { module: tag, action: index }
#   requirements:
#     sf_method: [GET]

# tag_notfound:
#   url: /tag/nao-encontrado
#   param: { module: tag, action: notFound }

# Modulo sitemap
sitemap:
  url: /sitemap.:sf_format
  param: { module: sitemap, action: index}
  requirements:
    sf_format: xml
    sf_method: [GET]

sitemap_type:
  url: /sitemap/:type.:sf_format
  param: { module: sitemap, action: maps}
  requirements:
    sf_format: xml
    sf_method: [GET]