# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    error_reporting:        ~
    cache:                  true
    etag:                   false
    logging_enabled:        false
    no_script_name:         true
    web_debug:              false

dev:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT | E_NOTICE) & ~E_DEPRECATED)."\n" ?>
    cache:                  false
    etag:                   false
    logging_enabled:        true
    no_script_name:         false
    web_debug:              false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT | E_NOTICE) & ~E_DEPRECATED)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .actions:
    error_404_module:       site
    error_404_action:       notFound

  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            2222d1cf96b4f5d7c4f56589675e6b2491cabecc

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    # Compressed
    compressed:             true

    charset: utf-8
    standard_helpers: [Partial, Cache, Text, Url]
