# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  metas:
    charset: "utf-8"
    title: "Apartamentos em Higienópolis - Breno Homara Imóveis"
    description: "Breno Homara Imóveis é uma imobiliária localizada no bairro de Higienópolis que fica na região central de São Paulo. Temos diversos imóveis para venda. Apartamentos de 01, 02, 03, 04 ou mais dormitórios. Apartamentos com súites. Oferta de Imóveis em edifícios que possuem área de lazer. Apartamentos à venda em Higienópolis e Santa Cecília que possuem sacada e ou terraço."
    keywords: "apartamento, higienópolis, higienopolis, apartamentos em higienópolis, Breno, Homara, Imóveis, imóvel em higienopolis, venda imóveis, vende-se imóvel, imoveis, casa, apartamento, prédio, cobertura, mansão, alto padrão, fotos, pacaembu, santa cecilia, santa cecília, compra, venda, aluguel, locação, negociação, perdizes, são paulo, sao paulo, imóveis em são paulo, locação higienopolis, venda higienópolis, apartamento em higienópolis, apartamento em sao paulo, apartamento em são paulo, classificados, classificados de imóveis, imóveis, imovel, imoveis, casa, apartamento"
    author: "Thiago Lagden Magalhães"
    language: en
    viewport: "width=device-width,initial-scale=1"

  stylesheets:
    - screen.css
    - print.css

  javascripts:
    # Mootools
    - vendor/mootools/mootools-core.js
    - vendor/mootools/mootools-more.js
    # jQuery
    - vendor/jquery/jquery.js
    # jQuery - Plugins
    - vendor/jquery/plugins/headsupgrid/hugrid.js
    - vendor/jquery/plugins/headsupgrid/init.js
    # jQuery - Plugins - Fancybox
    - vendor/jquery/plugins/fancybox/jquery.easing-1.3.pack.js
    - vendor/jquery/plugins/fancybox/jquery.mousewheel-3.0.6.pack.js
    - vendor/jquery/plugins/fancybox/jquery.fancybox.pack.js
    # Libs
    - plugins.js
    - script.js

  has_layout:     true
  layout:         layout