# User
User:
  actAs:
    Timestampable: ~
  indexes:
    login_index: { fields: [login, password] }
  columns:
    name: { type: string(255), notnull: true }
    email: { type: string(255), notnull: true, unique: true }
    phone: { type: string(50) }
    login: { type: string(255), notnull: true, unique: true }
    password: { type: string(80), notnull: true }
    token_forgot: { type: string(40) }

# Seção
Section:
  actAs:
    Sortable: ~
    Sluggable:
      fields: [title]
      canUpdate: true
      unique: true
    Timestampable: ~
  columns:
    route: { type: string(255) }
    title: { type: string(255), notnull: true, unique: true }
    description: clob
    content: clob
    seo: clob
    is_active: { type: boolean, default: 0 }
  relations:
    Tag:
      refClass: SectionTag
      alias: Tags
      foreignAlias: Sections

# Conteúdo
Content:
  actAs:
    Sortable:
      uniqueBy: [section_id]
    Sluggable:
      fields: [title]
      canUpdate: true
      unique: true
    Timestampable: ~
  columns:
    section_id: { type: bigint }
    title: { type: string(255), notnull: true, unique: true }
    description: clob
    content: clob
    seo: clob
    is_active: { type: boolean, default: 0 }
  relations:
    Tag:
      refClass: ContentTag
      alias: Tags
      foreignAlias: Contents
    Section:
      local: section_id
      class: Section
      foreignAlias: Contents
      onDelete: 'SET NULL'

# Tag
Tag:
  actAs:
    Sluggable:
      fields: [name]
      canUpdate: true
      unique: true
  indexes:
    name_index: { fields: [name] }
  columns:
    name: { type: string(255), notnull: true, unique: true }

SectionTag:
  columns:
    tag_id: { type: bigint, primary: true }
    section_id: { type: bigint, primary: true }
  relations:
    Tag: { local: tag_id, onDelete: CASCADE }
    Section: { local: section_id, onDelete: CASCADE }
    
ContentTag:
  columns:
    tag_id: { type: bigint, primary: true }
    content_id: { type: bigint, primary: true }
  relations:
    Tag: { local: tag_id, onDelete: CASCADE }
    Content: { local: content_id, onDelete: CASCADE }
    
EstateTag:
  columns:
    tag_id: { type: bigint, primary: true }
    estate_id: { type: bigint, primary: true }
  relations:
    Tag: { local: tag_id, onDelete: CASCADE }
    Estate: { local: estate_id, onDelete: CASCADE }
    
EstateDisponibilidade:
  columns:
    disponibilidade_id: { type: bigint, primary: true }
    estate_id: { type: bigint, primary: true }
  relations:
    Disponibilidade: { local: disponibilidade_id, onDelete: CASCADE }
    Estate: { local: estate_id, onDelete: CASCADE }

EstateComplemento:
  columns:
    complemento_id: { type: bigint, primary: true }
    estate_id: { type: bigint, primary: true }
  relations:
    Complemento: { local: complemento_id, onDelete: CASCADE }
    Estate: { local: estate_id, onDelete: CASCADE }

# Imóvel
Estate:
  actAs:
    Sluggable:
      fields: [titulo]
      canUpdate: true
      unique: true
    Timestampable: ~
  indexes:
    estate_index: { fields: [referencia] }
  columns:
    titulo: { type: string(255), notnull: true}
    referencia: { type: string(255), notnull: true, unique: true }
    area_util: { type: integer, default: 0 }
    area_total: { type: integer, default: 0 }
    suites: { type: integer(1), default: 0 }
    empregadas: { type: integer(1), default: 0 }
    quartos: { type: integer(1), default: 0 }
    banheiros: { type: integer(1), default: 0 }
    vagas: { type: integer(1), default: 0 }
    iptu: { type: 'decimal(12, 2)', default: '0.00'}
    condominio: { type: 'decimal(12, 2)', default: '0.00'}
    price_sale: { type: 'decimal(12, 2)', default: '0.00'}
    price_rent: { type: 'decimal(12, 2)', default: '0.00'}
    descricao: clob
    destaque_chamada: clob
    destaque: { type: boolean, default: 0 }
    ativo: { type: boolean, default: 0 }
    ordem: { type: integer(3), default: 0 }
    seo: clob
    carga: clob
    neighborhood_id: { type: bigint }
    type_id: { type: bigint }
  relations:
    Neighborhood:
      local: neighborhood_id
      class: Neighborhood
      foreignAlias: Estates
      onDelete: 'SET NULL'
    Type:
      local: type_id
      class: Type
      foreignAlias: Estates
      onDelete: 'SET NULL'
    Tag:
      refClass: EstateTag
      alias: Tags
      foreignAlias: Estates
    Disponibilidade:
      refClass: EstateDisponibilidade
      alias: Disponibilidades
      foreignAlias: Estates
    Complemento:
      refClass: EstateComplemento
      alias: Complementos
      foreignAlias: Estates

# Complementos
Complemento:
  actAs:
    Timestampable: ~
  columns:
    name: { type: string(255), notnull: true }

# Disponibilidade
Disponibilidade:
  actAs:
    Timestampable: ~
  columns:
    name: { type: string(255), notnull: true }

# Tipo
Type:
  actAs:
    Timestampable: ~
  columns:
    name: { type: string(255), notnull: true }

# Bairro
Neighborhood:
  actAs:
    Timestampable: ~
  columns:
    city_id: { type: bigint }
    name: { type: string(255), notnull: true }
  relations:
    City:
      local: city_id
      class: City
      foreignAlias: Cities
      onDelete: CASCADE

# Cidade
City:
  actAs:
    Timestampable: ~
  columns:
    name: { type: string(255), notnull: true }

# Imagem
Image:
  actAs:
    Timestampable: ~
  columns:
    file: { type: string(255) }
    destaque: { type: boolean, default: 0 }
    external: { type: boolean, default: 0 }
    estate_id: { type: bigint }
  relations:
    Estate:
      local: estate_id
      class: Estate
      foreignAlias: Images
      onDelete: CASCADE

# Imagem Formato
Format:
  actAs:
    Sluggable: { fields: [name] }
  columns:
    name:  { type: string(255), unique: true }

# Imagem Version
ImageVersion:
  columns:
    image_id: { type: bigint, primary: true }
    format_id: { type: bigint, primary: true }
    file: { type: string(255) }
  relations:
    Image:
      local: image_id
      foreignAlias: Versions
      onDelete: CASCADE
    Format:
      local: format_id
      foreignAlias: Images
      onDelete: CASCADE

# Log
LogReport:
  actAs:
    Timestampable: ~
  columns:
    ip: { type: string(50) } # ipv4 || ipv6
    report_type: { type: enum, default: notice, values: ['notice', 'warning', 'error'] }
    action: { type: enum, default: read, values: ['create', 'read', 'update', 'delete', 'download'] }
    message: clob
    details: clob
    record_id: { type: bigint }
    user_id: bigint
  relations:
    User:
      local: user_id
      class: User
      foreignAlias: Logs
      onDelete: 'SET NULL'